### ISSUE TITLE
account for failed themoviedb requests

### ISSUE THREAD

**Issue by au5ton** [au5ton/hatsume#12]

**Comment by au5ton** [comment]
unhandledRejection:  TypeError: Cannot read property 'id' of undefined
    at fetch.then.then.tmdb_entry (/home/user/testing/hatsume/lib/content.js:115:66)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 TypeError: Cannot read property 'id' of undefined
    at fetch.then.then.tmdb_entry (/home/user/testing/hatsume/lib/content.js:115:66)
    at process._tickCallback (internal/process/next_tick.js:68:7)
