### ISSUE TITLE
getcontentfromimdb: failure

### ISSUE THREAD

**Issue by au5ton** [au5ton/hatsume#18]
https://www.imdb.com/title/tt1727444/

**Comment by au5ton** [comment]
after refreshing the tvdb api token (a separate issue):
```
⛔  unhandledRejection:  Error: No results for your query: map[tve.seriesId:undefined]
    at res.json.then (/home/telegrambots/production/hatsume/node_modules/node-tvdb/index.js:554:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
 { Error: No results for your query: map[tve.seriesId:undefined]
    at res.json.then (/home/telegrambots/production/hatsume/node_modules/node-tvdb/index.js:554:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   { url: 'https://api.thetvdb.com/series/undefined/episodes',
     status: 404,
     statusText: 'Not Found' } }
```

**Comment by au5ton** [comment]
not sure where this happened, but look out for this too:
```
⛔  getcontentfromimdb: failure                                                                                                                                                                             
⛔  getcontentfromimdb: failure                                                                                                                                                                             
⛔  TypeError: Cannot read property 'textContent' of null                                                                                                                                                   
    at fetch.then.then.body (/home/telegrambots/testing/hatsume/lib/content.js:230:107)                                                                                                                     
    at process._tickCallback (internal/process/next_tick.js:68:7)  
```
